image: 
  name: javh/immcantation:test-python
  username: $USERNAME
  password: $PASSWORD
  email: $EMAIL

pipelines:
  default:
    - step:
        script:
          - python3 setup.py install
          - python3 -m unittest
          
